# ESTE TIPO DE VARIABLES CONTIENEN TODOS LOS COARACTERES DE SU NOMBRE EN MAYUSCULAS
# ESTO PARA INDICARLE A LOS PROGRAMADORES QUE SU VALOR DURANTE EL CODIGO ES CONSTANTE

PI = 3.141516
MI_CURP = 'MASH900524HGRSLC07'